### ISSUE TITLE
Could not find a valid gem

### ISSUE THREAD

**Issue by christoga** [jekyll/jekyll-admin#113]
I get this error while installing jekyll-admin using `gem`:
```shell
ERROR:  Could not find a valid gem 'jekyll-admin' (>= 0) in any repository
```
I already add it to the `Gemfile`, and the `_config.yml`. Is there something that I'm doing wrong?

**Comment by DirtyF** [comment]
Initial release is currently on development, so thhe gem is not ready yet, but you can [install it locally](https://github.com/jekyll/jekyll-admin/blob/master/docs/development.md).

**Comment by christoga** [comment]
Thanks mate!

**Comment by christoga** [comment]
After installing that, I got this error:
```shell
> jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:356:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll-admin' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:331:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:331:in `verify_gemfile_dependencies_are_found!'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:200:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:184:in `resolve'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `specs_for'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by benbalter** [comment]
@christoga were you able to [follow these instructions](https://github.com/jekyll/jekyll-admin/blob/master/docs/development.md#running-jekyll-admin-locally) to get the test server working locally?

**Comment by christoga** [comment]
@benbalter I installed it locally by following the instructions, next step?

**Comment by benbalter** [comment]
@christoga after you've cloned down the repo and installed dependencies, the instructions I linked you to describe how to run the fixture site. My question was if you were able to do that?

**Comment by christoga** [comment]
@benbalter I can't.
When I run my jekyll site, I get the error that I written above👆

**Comment by benbalter** [comment]
> When I run my jekyll site

@christoga are you trying to run the interface against the fixture site (which the instructions describe) or against another site? If another site, I'm afraid the project is still under development, and prior to its initial release, we aren't yet able to support users running it in other environments, unless you're able to so yourself by pointing Bundler at the local checkout.

**Comment by christoga** [comment]
So.. you're telling me that jekyll-admin isn't ready to use in a normal
jekyll-site?

**Comment by DirtyF** [comment]
Thanks to @benbalter I managed to test locally `jekyll-admin` with a normal jekyll site: 

- Clone the `jekyll-admin` repo on your machine:

`git clone https://github.com/jekyll/jekyll-admin.git`

- Run `bundle config --local local.jekyll-admin /Complete/path/to/jekyll-admin` to tell bundler where the gem is
- Edit your Jekyll's `Gemfile` and add:

```
group :jekyll_plugins do
  gem "jekyll-admin", github: "jekyll/jekyll-admin", branch: "master"
 end
```

- Run `bundle installl`

You should see amongst the installed gems:
```
...
Using jekyll-admin 0.1.0 from git://github.com/jekyll/jekyll-admin.git (at /Complete/path/to/jekyll-admin@a70d726)
```

- run `bundle exec jekyll serve`
- run `open http://localhost:4000/admin/`

Enjoy the hard work 😓  of @mertkahyaoglu and @benbalter

**Comment by benbalter** [comment]
Theoretically,

```
group :jekyll_plugins do
  gem "jekyll-admin", path: `path-to-your-local-clone`
 end
```

Should also work.

**Comment by christoga** [comment]
Everything works well until.. this happen:
```
An error occurred while installing nokogiri (1.6.8), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.8'` succeeds before bundling.
```
Then I got this error when I install the nokogiri
```
ERROR:  Error installing nokogiri:
ERROR: Failed to build gem native extension.
```

Probably I should give up and wait for the Initial release😉

**Comment by christoga** [comment]
Now I cannot run/view my jekyll site locally, which really pisses me off.
```
WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find RedCloth-4.2.9 in any of the sources (Bundler::GemNotFound)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `specs_for'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```
