### ISSUE TITLE
Error Could Not Fetch The Config

### ISSUE THREAD

**Issue by ghost** [jekyll/jekyll-admin#620]
This error message appears on a new Jekyll install with gem Jekyll-admin on Mint 19.3 as soon as I go to localhost:4000/admin

https://user-images.githubusercontent.com/76087897/103343410-6df89900-4aa5-11eb-8c20-bc62607f4779.mp4

**Comment by ashmaroli** [comment]
@sebawrite Thank you for reporting this issue with an attached demonstration.
However, we still don't have sufficient information to debug your issue.

If you check the `Console` tab in the browser's `inspect` frame (Right-click on the browser's main window to see options), you'd see additional information.
Try serving the site with the `--trace` switch. Then if you check the terminal window after the error flashes, you may also see some additional info there:
```
bundle exec jekyll serve --trace
```

**Comment by sebawrite** [comment]
I apologize. I've lost the information. I had to reinstall everything.

**Comment by mmm8955405** [comment]
> This error message appears on a new Jekyll install with gem Jekyll-admin on Mint 19.3 as soon as I go to localhost:4000/admin
> 
>  jekyll-could-not-fetch-config.mp4

I have the same problem. I want to ask you how to solve it

**Comment by gabrielgaraujo** [comment]
@ashmaroli I've ran it with `--trace` and also checked the console and network tabs, no error are displayed whatsoever.

I've tried running it on docker and also installed ruby 2.7.5 and 3.1.1 locally to check if it had something to do with ruby version. None of my attempts were successful.

You can use my [repo](https://github.com/gabrielgaraujo/gabrielgaraujo.github.io) to run it using docker and replicate the issue.

**Comment by loudorge** [comment]
@ashmaroli Hi! I have the same problem. I'm running the app on docker. `--trace` shows me nothing, there's also nothing special in the browser console.

Error appears when I access or refresh "Posts" or "Pages" pages. If I switch between the two by clicking on the links in sidebar, the error doesn't occur. But each time it occurs, following line appears in my terminal (which runs `jekyll serve --watch --draft --trace`): **`jekyll-jekyll-1  | Configuration file: /srv/jekyll/_config.yml`**

It's funny because there doesn't seem to be anything wrong (so far, but I haven't written any posts from the admin yet), it's just that this notification is annoying.

![image](https://user-images.githubusercontent.com/107001718/173425402-05d88585-3948-41f4-b1e2-b39db2eecae3.png)

Could you please help me in finding where it could come from?

**Comment by n0kovo** [comment]
Did anyone figure out he problem here? I'm having the same issue.

**Comment by Snowmansir** [comment]
Same thing here! The console has nothing in it either. The configuration file can be edited and will be saved when edited through the admin/configuration editor

![image](https://user-images.githubusercontent.com/108475475/218268728-67518c80-852c-47ef-b190-c37e48c4df32.png)

**Comment by y377** [comment]
frist nano your `_config.yml`
```yaml
jekyll_admin:
  hidden_links:
    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: "posts"
```
so easy!

**Comment by Snowmansir** [comment]
https://jekyll.github.io/jekyll-admin/configs/ 
I rather not hide things from my menu's like you suggest, it seems like swiping dust under the carpet.

Can you enlighten me why you think this is the solution?

**Comment by ADTC** [comment]
@y377 what did you mean there? I have the same problem. No errors from browser console or trace option @ashmaroli

**Comment by Snowmansir** [comment]
> @y377 what did you mean there? I have the same problem. No errors from browser console or trace option @ashmaroli

This is optional, and not the reason for this. Sweeping under the rug at best.

**Comment by fiveRand** [comment]
> try your `_config.yml`
> 
> ```yaml
> jekyll_admin:
>   hidden_links:
>     - pages
>     - staticfiles
>     - datafiles
>     - configuration
>   homepage: "posts"
> ```
> 
> * [need repair ]
> * [don't repair ]

It worked! Thank you!

**Comment by alistaircom** [comment]
I have had the same error, as well as a couple of others when trying to use jekyll-admin.  Below you can see my bundle install of everything I am using in my site, as well as a trace of everything that happened when I was navigating the jekyll-admin site. In particular, I went to the main page of jekyll-admin, and received: 
<img width="346" alt="image" src="https://github.com/jekyll/jekyll-admin/assets/855160/c6e3ae47-0485-4dca-82b0-79f8e6176133">

Going to the Data Files menu option gives me this error:
<img width="348" alt="image" src="https://github.com/jekyll/jekyll-admin/assets/855160/d1e55d56-2cd3-4436-8444-79fd456a6cfc">

```
(base) me@mycomputer testsite % bundle install          
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Fetching tilt 2.2.0
Fetching mustermann 3.0.0
Fetching rack-protection 3.1.0
Fetching multi_json 1.15.0
Installing rack-protection 3.1.0
Installing multi_json 1.15.0
Installing tilt 2.2.0
Installing mustermann 3.0.0
Fetching sinatra 3.1.0
Installing sinatra 3.1.0
Fetching sinatra-contrib 3.1.0
Installing sinatra-contrib 3.1.0
Fetching jekyll-admin 0.11.1
Installing jekyll-admin 0.11.1
Bundle complete! 10 Gemfile dependencies, 43 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
(base) me@mycomputer testsite % bundle exec jekyll serve
Configuration file: /Users/me/Projects/Jekyll/testsite/_config.yml
            Source: /Users/me/Projects/Jekyll/testsite
       Destination: /Users/me/Projects/Jekyll/testsite/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /Users/me/Projects/Jekyll/testsite/_site/powerful-things-markdown-editor/index.html
                     - /Users/me/Projects/Jekyll/testsite/_posts/2019-01-24-powerful-things-markdown-editor.md
                     - /Users/me/Projects/Jekyll/testsite/_posts/2019-02-03-powerful-things-markdown-editor.md
                    
                    done in 0.718 seconds.
 Auto-regeneration: enabled for '/Users/me/Projects/Jekyll/testsite'
  JekyllAdmin mode: production
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
Configuration file: /Users/me/Projects/Jekyll/testsite/_config.yml
       Jekyll Feed: Generating feed for posts
      Regenerating: 1 file(s) changed at 2023-09-12 13:34:01
                    _posts/2023-09-12-making-it-through-another-summer.md
  Liquid Exception: undefined method `[]' for nil:NilClass @stats[filename][:time] += time ^^^^^^^ in /Users/me/Projects/Jekyll/testsite/_layouts/default.html
2023-09-12 13:34:01 - NoMethodError - undefined method `[]' for nil:NilClass

      @stats[filename][:time] += time
                      ^^^^^^^:
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer.rb:31:in `increment_time'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:73:in `ensure in measure_time'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:73:in `measure_time'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:129:in `render_liquid'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:192:in `render_layout'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:161:in `place_in_layouts'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:93:in `render_document'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:557:in `block (2 levels) in render_docs'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:556:in `each'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:556:in `block in render_docs'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:555:in `each_value'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:555:in `render_docs'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:210:in `render'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-admin-0.11.1/lib/jekyll-admin/file_helper.rb:25:in `write_file'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-admin-0.11.1/lib/jekyll-admin/server/collections.rb:36:in `block (2 levels) in <class:Server>'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1763:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1763:in `block in compile!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1066:in `block (3 levels) in route!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1084:in `route_eval'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1066:in `block (2 levels) in route!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1115:in `block in process_route'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1113:in `catch'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1113:in `process_route'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1064:in `block in route!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1061:in `each'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1061:in `route!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1185:in `block in dispatch!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `catch'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `invoke'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1180:in `dispatch!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:996:in `block in call!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `catch'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `invoke'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:996:in `call!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:985:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-protection-3.1.0/lib/rack/protection/xss_header.rb:20:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-protection-3.1.0/lib/rack/protection/path_traversal.rb:18:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-protection-3.1.0/lib/rack/protection/json_csrf.rb:28:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-protection-3.1.0/lib/rack/protection/base.rb:53:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-protection-3.1.0/lib/rack/protection/base.rb:53:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-protection-3.1.0/lib/rack/protection/frame_options.rb:33:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-2.2.8/lib/rack/null_logger.rb:11:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:219:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:2074:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1633:in `block in call'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1849:in `synchronize'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1633:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-2.2.8/lib/rack/handler/webrick.rb:95:in `service'
	/Users/me/.gem/ruby/3.1.4/gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
	/Users/me/.gem/ruby/3.1.4/gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
	/Users/me/.gem/ruby/3.1.4/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'
       Jekyll Feed: Generating feed for posts
          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /Users/me/Projects/Jekyll/testsite/_site/powerful-things-markdown-editor/index.html
                     - /Users/me/Projects/Jekyll/testsite/_posts/2019-01-24-powerful-things-markdown-editor.md
                     - /Users/me/Projects/Jekyll/testsite/_posts/2019-02-03-powerful-things-markdown-editor.md
                    
                    ...done in 0.388789 seconds.
                    
Configuration file: /Users/me/Projects/Jekyll/testsite/_config.yml
^C

%(base) me@mycomputer testsite % bundle exec jekyll serve --trace
Configuration file: /Users/me/Projects/Jekyll/testsite/_config.yml
            Source: /Users/me/Projects/Jekyll/testsite
       Destination: /Users/me/Projects/Jekyll/testsite/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /Users/me/Projects/Jekyll/testsite/_site/powerful-things-markdown-editor/index.html
                     - /Users/me/Projects/Jekyll/testsite/_posts/2019-01-24-powerful-things-markdown-editor.md
                     - /Users/me/Projects/Jekyll/testsite/_posts/2019-02-03-powerful-things-markdown-editor.md
                    
                    done in 0.748 seconds.
 Auto-regeneration: enabled for '/Users/me/Projects/Jekyll/testsite'
  JekyllAdmin mode: production
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
Configuration file: /Users/me/Projects/Jekyll/testsite/_config.yml
       Jekyll Feed: Generating feed for posts
      Regenerating: 1 file(s) changed at 2023-09-12 13:38:04
                    _posts/2023-09-12-making-it-through-another-summer.md
  Liquid Exception: undefined method `[]' for nil:NilClass @stats[filename][:time] += time ^^^^^^^ in /Users/me/Projects/Jekyll/testsite/_layouts/default.html
2023-09-12 13:38:04 - NoMethodError - undefined method `[]' for nil:NilClass

      @stats[filename][:time] += time
                      ^^^^^^^:
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer.rb:31:in `increment_time'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:73:in `ensure in measure_time'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:73:in `measure_time'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:129:in `render_liquid'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:192:in `render_layout'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:161:in `place_in_layouts'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:93:in `render_document'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:557:in `block (2 levels) in render_docs'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:556:in `each'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:556:in `block in render_docs'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:555:in `each_value'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:555:in `render_docs'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:210:in `render'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-admin-0.11.1/lib/jekyll-admin/file_helper.rb:25:in `write_file'
	/Users/me/.gem/ruby/3.1.4/gems/jekyll-admin-0.11.1/lib/jekyll-admin/server/collections.rb:36:in `block (2 levels) in <class:Server>'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1763:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1763:in `block in compile!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1066:in `block (3 levels) in route!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1084:in `route_eval'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1066:in `block (2 levels) in route!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1115:in `block in process_route'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1113:in `catch'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1113:in `process_route'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1064:in `block in route!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1061:in `each'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1061:in `route!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1185:in `block in dispatch!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `catch'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `invoke'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1180:in `dispatch!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:996:in `block in call!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `catch'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `invoke'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:996:in `call!'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:985:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-protection-3.1.0/lib/rack/protection/xss_header.rb:20:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-protection-3.1.0/lib/rack/protection/path_traversal.rb:18:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-protection-3.1.0/lib/rack/protection/json_csrf.rb:28:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-protection-3.1.0/lib/rack/protection/base.rb:53:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-protection-3.1.0/lib/rack/protection/base.rb:53:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-protection-3.1.0/lib/rack/protection/frame_options.rb:33:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-2.2.8/lib/rack/null_logger.rb:11:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:219:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:2074:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1633:in `block in call'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1849:in `synchronize'
	/Users/me/.gem/ruby/3.1.4/gems/sinatra-3.1.0/lib/sinatra/base.rb:1633:in `call'
	/Users/me/.gem/ruby/3.1.4/gems/rack-2.2.8/lib/rack/handler/webrick.rb:95:in `service'
	/Users/me/.gem/ruby/3.1.4/gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
	/Users/me/.gem/ruby/3.1.4/gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
	/Users/me/.gem/ruby/3.1.4/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'
       Jekyll Feed: Generating feed for posts
          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /Users/me/Projects/Jekyll/testsite/_site/powerful-things-markdown-editor/index.html
                     - /Users/me/Projects/Jekyll/testsite/_posts/2019-01-24-powerful-things-markdown-editor.md
                     - /Users/me/Projects/Jekyll/testsite/_posts/2019-02-03-powerful-things-markdown-editor.md
                    
                    ...done in 0.375412 seconds.
                    
^C%
(base) me@mycomputer testsite %
```

**Comment by alistaircom** [comment]
Really feeling like this might be a permissions problem.  I have tried recreating a Jekyll instance with zero plugins other than what comes with a vanilla install and I get the same error.  

I am wondering if perhaps this is an OS issue: I'm on MacOS Ventura 13.5.1.

Also, when I use the --trace switch when running Jekyll, is the output only to screen, or does it get piped to a file?

**Comment by alistaircom** [comment]
So, the error message itself is coming from the translation files (in this case, the English one is):
https://github.com/jekyll/jekyll-admin/blob/36fe05bcbfe8d40dc64901a74805b7cca2a2af56/src/translations/en.js#L25-L26

getFetchErrorMessage is only used in fetch.js, specifically in these two instances:
https://github.com/jekyll/jekyll-admin/blob/36fe05bcbfe8d40dc64901a74805b7cca2a2af56/src/utils/fetch.js#L5-L11

and 

https://github.com/jekyll/jekyll-admin/blob/36fe05bcbfe8d40dc64901a74805b7cca2a2af56/src/utils/fetch.js#L13-L43

I suspect there is a permissions issue going on here, as I don't know enough about the code to understand what is happening. However, all of the error messages I have received appear to be coming from this block of code, and I cannot determine why.

Other than @odi-um making a small change to this block a few years ago, the remainder was written by @mertkahyaoglu. Being as it worked for years, I feel like it has to do with changes to OS-level permissions, but that is only a guess.

I hope we can find a solution.

**Comment by y377** [comment]
I’ll follow up on this question later, as I’m currently busy with other things. The author is no longer updating. Guys, we can only rely on ourselves.

**Comment by edutrul** [comment]
> > try your `_config.yml`
> > ```yaml
> > jekyll_admin:
> >   hidden_links:
> >     - pages
> >     - staticfiles
> >     - datafiles
> >     - configuration
> >   homepage: "posts"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * [need repair ]
> > * [don't repair ]
> 
> It worked! Thank you!

This worked nice 🥳

**Comment by nanocodex** [comment]
I'm still running into the

>  Error: Could not fetch the config

problem, and unfortunately



> try your `_config.yml`
> 
> ```yaml
> jekyll_admin:
>   hidden_links:
>     - pages
>     - staticfiles
>     - datafiles
>     - configuration
>   homepage: "posts"
> ```
> 
>     * [need repair ]
> 
>     * [don't repair ]

didn't help solve it. Has anyone else found a better workaround or a solution yet?

**Comment by vcavallo** [comment]
This gemfile (snippet) works for me:

```
gem 'sinatra-contrib', '~> 2.0'
gem 'rack-protection', '~> 2.0'

group :jekyll_plugins do
  gem 'jekyll-admin'
end
```

using jekyll 4.3.3 and jekyll-admin 0.11.1

**Comment by willhbr** [comment]
I believe this is because of [this destructuring](https://github.com/jekyll/jekyll-admin/blob/d29003e99d572282f82a47babf69eeb7b3d48598/src/containers/App.js#L35) in `App.js`. It gets compiled to:

```javascript
var t = this.props,
a = t.config.content,
n = a.jekyll_admin.homepage,
r = a.collections,
i = t.router,
c = i.getCurrentLocation().pathname;
```

So if you don't have `jekyll_admin.homepage` configured in your `_config.yml` file, this will fail. IIUC, Jekyll Admin will also only read `_config.yml` and not other config files provided with `--config` (as per [this PR](https://github.com/jekyll/jekyll-admin/pull/322)) so if (like me) you have the `jekyll_admin` block in a different file, it'll still fail.

It would be nice to include the actual error message in [the failure notification](https://github.com/jekyll/jekyll-admin/blob/d29003e99d572282f82a47babf69eeb7b3d48598/src/utils/fetch.js#L38) which would make reported failures clearer.
