### ISSUE TITLE
@server.mount "/admin", Rack::Handler::WEBrick, JekyllAdmin::StaticServer

### ISSUE THREAD

**Issue by jack1ripper** [jekyll/jekyll-admin#716]
### Description:
I build a brand new blog with jekyll ,  and then a added jekyll-admin , and
my app crashed with sass warnings and errors blow:

**sass warnings**
```
 myblog  bundle exec jekyll serve
logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
csv was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add csv to your Gemfile or gemspec to silence this warning.
/Users/dengxiang/.rubies/ruby-3.3.5/lib/ruby/3.3.0/json/common.rb:3: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Configuration file: /Users/dengxiang/Jekyll/myblog/_config.yml
            Source: /Users/dengxiang/Jekyll/myblog
       Destination: /Users/dengxiang/Jekyll/myblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 81.6%)
color.adjust($color, $lightness: 40%)

More info: https://sass-lang.com/d/color-functions

   ╷
18 │ $grey-color-light: lighten($grey-color, 40%) !default;
   │                    ^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    minima.scss 18:20                                    @import
    /Users/dengxiang/Jekyll/myblog/assets/main.scss 1:9  root stylesheet
Deprecation Warning: darken() is deprecated. Suggestions:

color.scale($color, $lightness: -49.0384615385%)
color.adjust($color, $lightness: -25%)

More info: https://sass-lang.com/d/color-functions

   ╷
19 │ $grey-color-dark:  darken($grey-color, 25%) !default;
   │                    ^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    minima.scss 19:20                                    @import
    /Users/dengxiang/Jekyll/myblog/assets/main.scss 1:9  root stylesheet
Deprecation Warning: darken() is deprecated. Suggestions:
```

**error**
```
  /Users/James/.gem/ruby/3.3.5/gems/jekyll-admin-0.11.1/lib/jekyll/commands/serve.rb:23:in `jekyll_admin_monkey_patch': uninitialized constant Rack::Handler (NameError)
          @server.mount "/admin", Rack::Handler::WEBrick, JekyllAdmin::StaticServer
                                      ^^^^^^^^^
        from /Users/dengxiang/.gem/ruby/3.3.5/gems/jekyll-admin-0.11.1/lib/jekyll/commands/serve.rb:15:in `start_up_webrick'
        from /Users/dengxiang/.gem/ruby/3.3.5/gems/jekyll-4.3.4/lib/jekyll/commands/serve.rb:102:in `process'
        from /Users/dengxiang/.gem/ruby/3.3.5/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /Users/dengxiang/.gem/ruby/3.3.5/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `each'

```

### Tell us a bit about yourself:
```
Gems included by the bundle:
  * addressable (2.8.7)
  * base64 (0.2.0)
  * bigdecimal (3.1.8)
  * bundler (2.5.21)
  * colorator (1.1.0)
  * concurrent-ruby (1.3.4)
  * em-websocket (0.5.3)
  * eventmachine (1.2.7)
  * ffi (1.17.0)
  * forwardable-extended (2.6.0)
  * google-protobuf (4.28.2)
  * http_parser.rb (0.8.0)
  * i18n (1.14.6)
  * jekyll (4.3.4)
  * jekyll-admin (0.11.1)
  * jekyll-feed (0.17.0)
  * jekyll-sass-converter (3.0.0)
  * jekyll-seo-tag (2.8.0)
  * jekyll-watch (2.2.1)
  * kramdown (2.4.0)
  * kramdown-parser-gfm (1.1.0)
  * liquid (4.0.4)
  * listen (3.9.0)
  * mercenary (0.4.0)
  * minima (2.5.2)
  * multi_json (1.15.0)
  * mustermann (3.0.3)
  * pathutil (0.16.2)
  * public_suffix (6.0.1)
  * rack (3.1.7)
  * rack-protection (4.0.0)
  * rack-session (2.0.0)
  * rackup (2.1.0)
  * rake (13.2.1)
  * rb-fsevent (0.11.2)
  * rb-inotify (0.11.1)
  * rexml (3.3.8)
  * rouge (4.4.0)
  * ruby2_keywords (0.0.5)
  * safe_yaml (1.0.5)
  * sass-embedded (1.79.5)
  * sinatra (4.0.0)
  * sinatra-contrib (4.0.0)
  * terminal-table (3.0.2)
  * tilt (2.4.0)
  * unicode-display_width (2.6.0)
  * webrick (1.8.2)

```

* Version of JekyllAdmin I'm using <HINT: use `bundle show` to check>:    0.11.1
* Version of Jekyll I'm using <HINT: use `bundle show` to check>: 4.3.4
* Version of NodeJS I'm using <HINT: use `node -v` to check>:  v16.19.1

* Operating System <e.g. OS X, Windows>: mac os
* Browser <e.g, Safari, Chrome>: chrome

### Steps to reproduce:

follow jekyll guide build my app , and then add admin plugin  then it happens

### I expected the following:

I expect I could open admin GUI with :4000/admin

### But got the following, instead:

I tried add rackup into gem ,still the same.

this is the my gemfile
```
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-admin"    (the is the line I added into the file)
  gem "rackup"             (the is the line I added into the file)
end
```
this is my config.yml
```
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin  (the is the only line I added into the file)
```
then I bundle install and jekyll S,  and fail

**Comment by ashmaroli** [comment]
Thanks for the detailed report, @jack1ripper. This issue is being handled and has been previously reported via #705

**Comment by Ches-ctrl** [comment]
Same issue for me

**Comment by ashmaroli** [comment]
Addressed via #715

**Comment by drewdaemon** [comment]
@ashmaroli has the fix been released in some form?

**Comment by ashmaroli** [comment]
@drewdaemon There hasn't been an official release with this patch but since you enquired about a release in any form, you may download an unofficial archive [here](https://github.com/jekyll/jekyll-admin/actions/runs/13071820354/artifacts/2516382034) or you may download the same from the workflow summary page of the *Build Gem Artifact* workflow in this repository.

However, do note that while the gem archive can be installed or unpacked like any gem package, the version string within hasn't been updated and will overwrite an existing installation of the plugin (which would have been downloaded from Rubygems server).

The archive download link is temporary and will expire automatically.

I will try and ship an official release sometime in February.

**Comment by alyxdeburca** [comment]
Forgive my ignorance but how do I reference this in my Gemfile?

**Comment by drewdaemon** [comment]
@alyxdeburca I'm no Ruby expert, but I it worked for me to run `gem install path/to/downloaded/gem`

**Comment by dev3java** [comment]
> I will try and ship an official release sometime in February.

I have the same problem. Thank you for your hard work.
